### ISSUE TITLE
Connection Error { MongoError: failed to connect to server [CLUSTER-96bea.mongodb.net:27017]

### ISSUE THREAD

**Issue by danielwerg** [lukechilds/keyv-mongo#30] opened 2019-04-25 17:58 UTC
```
Connection Error { MongoError: failed to connect to server [CLUSTER-96bea.mongodb.net:27017] on first connect [MongoError: getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net CLUSTER-96bea.mongodb.net:27017]
```
~ I replaced actual cluster name with "CLUSTER".

I'm keep getting this error, with both example code and custom provider:

```javascript
  const Keyv = require('keyv');

  const keyv = new Keyv(`mongodb+srv://${username}:${process.env.mongopw}@${username}-96bea.mongodb.net/${dbName}`);
  keyv.on('error', err => console.log('Connection Error', err));
```

```javascript
  const Keyv = require('keyv');
  const KeyvMongo = require('@keyv/mongo');

  const keyvMongo = new KeyvMongo(`mongodb+srv://${username}:${process.env.mongopw}@${username}-96bea.mongodb.net/${dbName}`);
  const keyv = new Keyv({ store: keyvMongo });
  keyv.on('error', err => console.log('Connection Error', err));
```

And I'm pretty sure url is correct, i'm using it with other npm module

**Comment by lukechilds** [comment] 2019-04-26 11:46
Can you try replacing `mongodb+srv://` with `mongodb://`?

**Comment by danielwerg** [comment] 2019-04-27 06:43
It gives same error:
```
failed to connect to server [CLUSTER-96bea.mongodb.net:27017] on first connect [MongoError: getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net CLUSTER-96bea.mongodb.net:27017]
```

**Comment by danielwerg** [comment] 2019-05-05 20:13
I messed up thing using `mongodb+srv://` will give me this:
```
internal/validators.js:107
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "id" argument must be of type string. Received type undefined
```

**Comment by SpeedyCraftah** [comment] 2019-05-11 16:30
Same problem, mlab works very well however it's shutting down

**Comment by lukechilds** [comment] 2019-05-12 10:18
@danielwerg where is `internal/validators.js` coming from?

Is that your application code, another package or something internal to Node.js?

@SpeedyCraftah Can you explain what you mean by:

>works very well however it's shutting down

**Comment by danielwerg** [comment] 2019-05-14 09:59
@lukechilds I created a separate folder for it, https://i.imgur.com/BQeoXYr.png it's all code a have
So I suppose it's node.js.

**Comment by lukechilds** [comment] 2019-05-14 10:04
Ok thanks. And you get the exact same error when you instantiate `KeyvMongo` directly?

**Comment by danielwerg** [comment] 2019-05-14 10:21
`index.js`:
```js
require('dotenv').config();

let un = process.env.un, dbName = process.env.dbName, password = process.env.mongopw;

const Keyv = require('keyv');
const KeyvMongo = require('@keyv/mongo');

const keyvMongo = new KeyvMongo(`mongodb+srv://${un}:${password}@${un}-96bea.mongodb.net/${dbName}`);
const keyv = new Keyv({ store: keyvMongo });
keyv.on('error', err => console.log(err));

```
full error:
```
Error [MongoError]: failed to connect to server [CLUSTER-96bea.mongodb.net:27017] on first connect [Error: getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  name: 'MongoError',
  message: 'getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net'
}]
    at Pool.<anonymous> (C:\Users\Daniel\Documents\projects\test\keyv\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:196:13)
    at Connection.<anonymous> (C:\Users\Daniel\Documents\projects\test\keyv\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:284:20)
    at Connection.emit (events.js:196:13)
    at Socket.<anonymous> (C:\Users\Daniel\Documents\projects\test\keyv\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:284:20)
    at Socket.emit (events.js:196:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) {
  name: 'MongoError',
  message: 'failed to connect to server [CLUSTER-96bea.mongodb.net:27017] on first ' +
    'connect [Error: getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net\n    at ' +
    'GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {\n  name: ' +
    "'MongoError',\n  message: 'getaddrinfo ENOTFOUND " +
    "CLUSTER-96bea.mongodb.net'\n}]"
}
```
I replaced cluster name with `CLUSTER` just in case
Sorry for late replies, Im not getting notification for some reason.

**Comment by lukechilds** [comment] 2019-05-14 10:28
Can you try using `mongojs` directly.

Don't `npm install mongojs` though, just use `require('mongojs')` in the same directory so it uses the version bundled with `keyv-mongo`.

That should let us know for sure if the issue is in `keyv-mongo` or `mongojs`.

**Comment by danielwerg** [comment] 2019-05-14 10:43
```js
const mongojs = require('mongojs');
// const db = mongojs('mydb');
const db = mongojs(`mongodb+srv://${un}:${password}@${un}-96bea.mongodb.net/${dbName}`, ['db']);

db.on('error', function (err) {
  console.log('database error', err);
});

db.on('connect', function () {
  console.log('database connected');
});
```
am I do something wrong? Im not getting any output :/

**Comment by lukechilds** [comment] 2019-05-14 10:49
Can you query?

If your collection is called `db` then you should do:

```js
// find everything
db.db.find(function (err, docs) {
	// docs is an array of all the documents in mycollection
})
```

**Comment by danielwerg** [comment] 2019-05-14 10:52
```
database error Error [MongoError]: failed to connect to server [CLUSTER-96bea.mongodb.net:27017] on first connect [Error: getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {
  name: 'MongoError',
  message: 'getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net'
}]
    at Pool.<anonymous> (C:\Users\Daniel\Documents\projects\test\keyv\node_modules\mongodb-core\lib\topologies\server.js:336:35)
    at Pool.emit (events.js:196:13)
    at Connection.<anonymous> (C:\Users\Daniel\Documents\projects\test\keyv\node_modules\mongodb-core\lib\connection\pool.js:280:12)
    at Object.onceWrapper (events.js:284:20)
    at Connection.emit (events.js:196:13)
    at Socket.<anonymous> (C:\Users\Daniel\Documents\projects\test\keyv\node_modules\mongodb-core\lib\connection\connection.js:189:49)
    at Object.onceWrapper (events.js:284:20)
    at Socket.emit (events.js:196:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3) {
  name: 'MongoError',
  message: 'failed to connect to server [CLUSTER-96bea.mongodb.net:27017] on first ' +
    'connect [Error: getaddrinfo ENOTFOUND CLUSTER-96bea.mongodb.net\n    at ' +
    'GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:60:26) {\n  name: ' +
    "'MongoError',\n  message: 'getaddrinfo ENOTFOUND " +
    "CLUSTER-96bea.mongodb.net'\n}]"
}
```
here it is

**Comment by lukechilds** [comment] 2019-05-15 08:47
Ok so this looks like the issue is not with `keyv-mongo` but with `mongojs`.

I would suggest opening an issue on the `mongojs` repo.

I'll close this for now but feel free to re-open in the future if you think this is an issue with `keyv-mongo`.

**Closed by lukechilds** 2019-05-15 08:47 UTC

**Comment by danielwerg** [comment] 2019-05-15 21:02
thanks for trying to help, I'll do.

**Comment by Giuseppetm** [comment] 2020-06-05 14:17
Someone has a solution?

**Comment by SpeedyCraftah** [comment] 2020-08-20 01:13
Late response but this won't be fixed unless Luke changes the mongodb client (or mongojs fixes the issue but that seems unlikely). I may submit a pull request to change the client to Mongoose or just the plain mongodb client (recommended by mongodb atlas). Would be nice if @lukechilds gave confirmation that the PR will be merged if I do submit one.

**Comment by SpeedyCraftah** [comment] 2020-08-20 01:14
Though I havent yet checked if mongojs has fixed the issue in their latest version.

**Comment by thyagodorea** [comment] 2020-11-17 20:51
Same error here! Nothing yet?

**Comment by SebiTalent04** [comment] 2020-12-24 21:46
bump
same here

**Comment by PsiAphex** [comment] 2021-02-22 09:35
Same issue here

**Comment by SpeedyCraftah** [comment] 2021-02-22 09:39
Not much any of you can do, mongojs has been abandoned as well a keyv. I may make a pull request with a maintained mongodb driver being used instead of mongojs which you all can install.

**Comment by SpeedyCraftah** [comment] 2021-02-22 09:39
> Not much any of you can do, mongojs has been abandoned as well a keyv. I may make a pull request with a maintained mongodb driver being used instead of mongojs which you all can install.

Or a forked project. L

**Comment by PsiAphex** [comment] 2021-03-04 05:45
It might be possible to make a mongo adapter using the mongodb package and publish it to npm

**Comment by allandiego** [comment] 2021-04-04 02:53
I have created a custom mongoose adapter for mongo atlas

```ts
import { EventEmitter } from 'events';
import mongoose, { model, Schema, Model, Document } from 'mongoose';

interface IStore extends Document {
  _id: string;
  key: string;
  value: any;
  expiresAt: Date | null;
}

interface Options {
  uri: string;
  namespace: string;
}

export class KeyvMongoStore extends EventEmitter {
  private db: Model<IStore>;

  private options: any;

  constructor(options: Options) {
    super();
    this.options = options;

    const StoreSchema = new Schema({
      key: {
        type: String,
        required: true,
      },
      value: {
        type: Schema.Types.Mixed,
        required: true,
      },
      expiresAt: {
        type: Date,
        required: false,
        expires: 0,
      },
    });

    StoreSchema.index({ key: 1 }, { unique: true });
    StoreSchema.index({ expiresAt: 1 }, { expireAfterSeconds: true });

    if (mongoose.connection.readyState === 0) {
      mongoose
        .connect(this.options.uri, {
          useNewUrlParser: true,
          useUnifiedTopology: true,
          useFindAndModify: false,
          useCreateIndex: true,
        })
        .then(() => {
          this.db = model(this.options.namespace ?? 'keyv', StoreSchema);
        })
        .catch(error => console.log(error));
    } else {
      this.db = model(this.options.namespace ?? 'keyv', StoreSchema);
    }
  }

  async get(key: string): Promise<any> {
    const record = await this.db.findOne({ key }).lean();

    if (record === null) {
      return undefined;
    }
    return record.value;
  }

  async set(
    key: string,
    value: any,
    ttl: number | undefined,
  ): Promise<boolean> {
    const expiresAt =
      typeof ttl === 'number' ? new Date(Date.now() + ttl) : null;

    const record = await this.db.findOneAndUpdate(
      { key },
      { key, value, expiresAt },
      { upsert: true },
    );

    return !!record;
  }

  async delete(key: string): Promise<boolean> {
    if (typeof key !== 'string') {
      return false;
    }

    const record = await this.db.findOneAndDelete({ key }).lean();
    return !(record === null);
  }

  async clear(): Promise<void> {
    await this.db.deleteMany({
      key: new RegExp(`^${this.options.namespace}:`),
    });
  }
}
```

Use
```ts
import Keyv from 'keyv';

function run() {
const store = new Keyv({
  namespace: 'settings',
  store: new KeyvMongoStore({
    uri: process.env.MONGODB_URI,
    namespace: 'settings',
  }),
});

await store.set('v1', '123');
await store.get('v1');
}

run();

```
